# Generated by Django 5.0 on 2023-12-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('telephon_number', models.CharField(max_length=255)),
                ('emeil', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('competencies', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
