# Generated by Django 5.0 on 2024-01-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resume_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories'),
        ),
    ]
