# Generated by Django 5.0 on 2024-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_uploadfiles_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
